apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
  - host: moded5.uri.fr
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path:
